// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNLGFmLucL18dQBpzrfXWP7YN8wt2PZ3k',
    appId: '1:268988164591:web:824b0b0d5f6c2e4c5f2e1a',
    messagingSenderId: '268988164591',
    projectId: 'prm393-coffemanagement',
    authDomain: 'prm393-coffemanagement.firebaseapp.com',
    storageBucket: 'prm393-coffemanagement.firebasestorage.app',
    measurementId: 'G-L5R154KV0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJBjOC6ZGlYLDy4chqdh5olF2BAEWXgVU',
    appId: '1:268988164591:android:545609c977bdd98d5f2e1a',
    messagingSenderId: '268988164591',
    projectId: 'prm393-coffemanagement',
    storageBucket: 'prm393-coffemanagement.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNLGFmLucL18dQBpzrfXWP7YN8wt2PZ3k',
    appId: '1:268988164591:web:e2621ff421d7885e5f2e1a',
    messagingSenderId: '268988164591',
    projectId: 'prm393-coffemanagement',
    authDomain: 'prm393-coffemanagement.firebaseapp.com',
    storageBucket: 'prm393-coffemanagement.firebasestorage.app',
    measurementId: 'G-201K1F7TYC',
  );
}
